spring.application.name=foodiesapi

# FIXED: Thêm dấu # ở đầu dòng dưới để tắt MongoDB, chống xung đột hệ thống
# spring.data.mongodb.uri=mongodb://localhost:27017/foodies

# Chạy API backend ở cổng 8080 đúng như file Context React gọi sang
server.port=8080

# Cấu hình cơ sở dữ liệu ảo tự động tạo bảng lưu trữ trong bộ nhớ RAM
spring.datasource.url=jdbc:h2:mem:foodiesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update