spring.application.name=foodiesapi

# Chạy API backend ở cổng 8080 đúng như file Context React gọi sang
server.port=8080

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://miniquesosuy:${DB_PASSWORD:nguoidephaysuy123}@cluster0.kyjdxfb.mongodb.net/CatExpress?retryWrites=true&w=majority&appName=Cluster0&authSource=admin
spring.data.mongodb.auto-index-creation=true