spring.application.name=groceries

#mongodb configuration
#spring.mongodb.uri=mongodb://localhost:27017/groceries
spring.mongodb.uri=mongodb+srv://miniquesosuy:${DB_PASSWORD}@cluster0.kyjdxfb.mongodb.net/CatExpress?retryWrites=true&w=majority&appName=Cluster0&authSource=admin
#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=eu-north-1
aws.s3.bucketname=groceries-goods

logging.level.org.springframework.security=DEBUG

jwt.secret.key = MySuperSecretKeyForJwtAuthentication2026!!

#razorpay configuration
razorpay_key = ${RAZORPAY_KEY}
razorpay_secret = ${RAZORPAY_SECRET}
