spring.application.name=foodie-backend
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/foodie_db
spring.data.mongodb.auto-index-creation=true

jwt.secret=FoodieApp_Super_Secret_Key_2025_v52_mustbe256bitslong!!
jwt.expiration=86400000

# CORS: allow all 3 frontends
cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:5175

# Razorpay (replace with real keys for production)
razorpay.key.id=demo_key
razorpay.key.secret=demo_secret

logging.level.com.foodie=DEBUG
